
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ghibli_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'ghibli'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]

target-path: "target"
log-path: "logs"
packages-install-path: "dbt_packages"

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Require minimum dbt version
require-dbt-version: ">=1.6.0"

# Project-wide variables (extensible for future stories)
vars: {}

# Model materialization configuration
# Staging: views (lightweight, always fresh)
# Intermediate: ephemeral (not materialized, CTEs only)
# Marts: tables (fast queries, production-ready)
models:
  ghibli_project:
    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: ephemeral
      +schema: intermediate

    marts:
      +materialized: table
      +schema: marts
